### ISSUE TITLE
Acrescentar mais campos no objeto Tournament

### ISSUE THREAD

**Issue by douglastaquary** [douglastaquary/boom-api#3]
```json
{
  "minPrice": "string",
  "name": "string",
  "id": "string",
  "maxPrice": "string",
  "prize": {
    "imgUrl": "string",
    "name": "string",
    "value": "string"
  }
}
```

Aqui iremos precisar de quantas pessoas ja estão escritos e quantas vagas ainda tem para iniciar a partida.

Aqui já temos um `GAP`:
• Se são vários rodadas diferentes com o "mesmo" prêmio: ex.: `5, 50, 300, 1000, 2000`  pessoas, na resposta da requisição já teria que vir a quantidade de grupos explícitos. Tipo: no `JSON` ja vir quantas rodadas esse cara tem e quantos inscritos ja tem em cada rodada, isso nesse caso seria outro objeto que faria parte desse `JSON`. Algo como:

```json
{
 "games": [{"participando": 250,  "maxNumber": 300, "ticketPrice": 10.0} ],
  "minPrice": "string",
  "name": "string",
  "id": "string",
  "maxPrice": "string",
  "prize": {
    "imgUrl": "string",
    "name": "string",
    "value": "string"
  }
}
```

**Comment by tOOlmaker-equalsp** [comment]
Resolvida #6
